{
 "title": "Cloudflare-GraphQL-Logpush-Success-Account",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   { "name": "accountTag" }
  ]
 },
 "panels": [
  {
   "title": "Logpush Success Sum Records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {records}\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum Records per JobID",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.jobId",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "groupBy": "dimensions.jobId",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(orderBy: [jobId_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {records}\n        dimensions{\n          jobId\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.jobId",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "groupBy": "dimensions.jobId",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(orderBy: [datetimeHour_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {records}\n        dimensions{\n          jobId\n          time: datetimeHour\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum Records per DestType",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.destinationType",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "groupBy": "dimensions.destinationType",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(orderBy: [destinationType_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {records}\n        dimensions{\n          destinationType\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {\n          bytes\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum Bytes per JobID",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.jobId",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "groupBy": "dimensions.jobId",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(orderBy: [jobId_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {bytes}\n        dimensions{\n          jobId\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.jobId",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "groupBy": "dimensions.jobId",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(orderBy: [datetimeHour_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {bytes}\n        dimensions{\n          jobId\n          time: datetimeHour\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum Bytes per DestType",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.destinationType",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "groupBy": "dimensions.destinationType,",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(orderBy: [destinationType_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {bytes}\n        dimensions{\n          destinationType\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum BytesCompressed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {\n          bytesCompressed\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum BytesCompressed per JobID",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.jobId",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "groupBy": "dimensions.jobId",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(orderBy: [jobId_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {bytesCompressed}\n        dimensions{\n          jobId\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum BytesCompressed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.jobId",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "groupBy": "dimensions.jobId",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(orderBy: [datetimeHour_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {bytesCompressed}\n        dimensions{\n          jobId\n          time: datetimeHour\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Logpush Success Sum Bytes per DestType",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.destinationType",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.logpush",
     "endTimePath": "endTime",
     "groupBy": "dimensions.destinationType,",
     "queryText": "{\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      logpush: logpushHealthAdaptiveGroups(orderBy: [destinationType_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", status_lt: 300, final: 1}) {\n        sum {bytesCompressed}\n        dimensions{\n          destinationType\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  }
 ]
}