{
 "title": "Cloudflare-GraphQL-R2",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   { "name": "accountTag" }
  ]
 },
 "panels": [
  {
   "title": "Account Total Storage Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.storage",
     "endTimePath": "endTime",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      storage: r2StorageAdaptiveGroups(orderBy: [bucketName_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\",}) {\n        dimensions {\n          bucketName\n        }\n        max {\n          metadataSize\n          payloadSize\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Account Total Storage Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.storage",
     "endTimePath": "endTime",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      storage: r2StorageAdaptiveGroups(orderBy: [bucketName_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\",}) {\n        dimensions {\n          bucketName\n        }\n        max {\n          metadataSize\n          objectCount\n          payloadSize\n          uploadCount\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Bucket Total Storage Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.storage",
     "endTimePath": "endTime",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      storage: r2StorageAdaptiveGroups(orderBy: [bucketName_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\",}) {\n        dimensions {\n          bucketName\n        }\n        max {\n          metadataSize\n          payloadSize\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Bucket Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.storage",
     "endTimePath": "endTime",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      storage: r2StorageAdaptiveGroups(orderBy: [datetimeHour_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\",}) {\n        dimensions {\n          bucketName\n          time: datetimeHour\n        }\n        max {\n          metadataSize\n          payloadSize\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Account Total Class A Ops",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.classA",
     "endTimePath": "endTime",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      classA: r2OperationsAdaptiveGroups(limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", actionStatus: \"success\", actionType_in: [\"ListBuckets\", \"PutBucket\", \"ListObjects\", \"PutObject\", \"CopyObject\", \"CompleteMultipartUpload\", \"CreateMultipartUpload\", \"UploadPart\", \"UploadPartCopy\", \"PutBucketEncryption\", \"ListMultipartUploads\"]}) {\n        dimensions {\n          actionType\n        }\n        sum {\n          requests\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Account Total Class A Ops",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.actionType",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.classA",
     "endTimePath": "endTime",
     "groupBy": "dimensions.actionType",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      classA: r2OperationsAdaptiveGroups(limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", actionStatus: \"success\", actionType_in: [\"ListBuckets\", \"PutBucket\", \"ListObjects\", \"PutObject\", \"CopyObject\", \"CompleteMultipartUpload\", \"CreateMultipartUpload\", \"UploadPart\", \"UploadPartCopy\", \"PutBucketEncryption\", \"ListMultipartUploads\"]}) {\n        dimensions {\n          actionType\n        }\n        sum {\n          requests\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Bucket Total Class A Ops",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.classA",
     "endTimePath": "endTime",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      classA: r2OperationsAdaptiveGroups(limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", actionStatus: \"success\", actionType_in: [\"ListBuckets\", \"PutBucket\", \"ListObjects\", \"PutObject\", \"CopyObject\", \"CompleteMultipartUpload\", \"CreateMultipartUpload\", \"UploadPart\", \"UploadPartCopy\", \"PutBucketEncryption\", \"ListMultipartUploads\"]}) {\n        dimensions {\n          bucketName\n        }\n        sum {\n          requests\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Class A Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "aliasBy": "$field_dimensions.actionType",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.classA",
     "endTimePath": "endTime",
     "groupBy": "dimensions.actionType",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      classA: r2OperationsAdaptiveGroups(orderBy: [datetimeHour_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", actionStatus: \"success\", actionType_in: [\"ListBuckets\", \"PutBucket\", \"ListObjects\", \"PutObject\", \"CopyObject\", \"CompleteMultipartUpload\", \"CreateMultipartUpload\", \"UploadPart\", \"UploadPartCopy\", \"PutBucketEncryption\", \"ListMultipartUploads\"]}) {\n        dimensions {\n          actionType\n          time: datetimeHour\n        }\n        sum {\n          requests\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Account Total Class B Ops",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.classB",
     "endTimePath": "endTime",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      classB: r2OperationsAdaptiveGroups(limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", actionStatus: \"success\", actionType_in: [\"HeadBucket\", \"HeadObject\", \"GetObject\", \"ReportUsageSummary\", \"GetBucketEncryption\", \"GetBucketLocation\"]}) {\n        dimensions {\n          actionType\n        }\n        sum {\n          requests\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Account Total Class B Ops",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aliasBy": "$field_dimensions.actionType",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.classB",
     "endTimePath": "endTime",
     "groupBy": "dimensions.actionType",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      classB: r2OperationsAdaptiveGroups(limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", actionStatus: \"success\", actionType_in: [\"HeadBucket\", \"HeadObject\", \"GetObject\", \"ReportUsageSummary\", \"GetBucketEncryption\", \"GetBucketLocation\"]}) {\n        dimensions {\n          actionType\n        }\n        sum {\n          requests\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Bucket Total Class B Ops",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.classB",
     "endTimePath": "endTime",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      classB: r2OperationsAdaptiveGroups(limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", actionStatus: \"success\", actionType_in: [\"HeadBucket\", \"HeadObject\", \"GetObject\", \"ReportUsageSummary\", \"GetBucketEncryption\", \"GetBucketLocation\"]}) {\n        dimensions {\n          bucketName\n        }\n        sum {\n          requests\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Class B Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "aliasBy": "$field_dimensions.actionType",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.classB",
     "endTimePath": "endTime",
     "groupBy": "dimensions.actionType",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      classB: r2OperationsAdaptiveGroups(orderBy: [datetimeHour_ASC], limit: 1000, filter: {date_geq: \"${__from:date:YYYY-MM-DD}\",date_leq: \"${__to:date:YYYY-MM-DD}\", actionStatus: \"success\", actionType_in: [\"HeadBucket\", \"HeadObject\", \"GetObject\", \"ReportUsageSummary\", \"GetBucketEncryption\", \"GetBucketLocation\"]}) {\n        dimensions {\n          actionType\n          time: datetimeHour\n        }\n        sum {\n          requests\n        }\n      }\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  }
 ]
}